version: '3.8'

services:
  webservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: node:18-alpine
    restart: always
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DB: '${MYSQL_DATABASE}'
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  mysql:
    image: mysql:8.0
    volumes:
      - webservice-mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 12
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9095:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 4050:3000
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_PATHS_PROVISIONING: '/etc/grafana/provisioning'
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: '/var/lib/grafana/dashboards/node.yml'
volumes:
  prometheus_data: {}
  grafana_data: {}
  webservice-mysql-data:
